# Config
name: libxml2
srcdir: ./workspace/src/libxml2
postfix:
  - .h
  - .hpp
  - .hxx
fuzzdict: ./workspace/dict/xml.dict
corpus_dir: ./workspace/corpus
# CppConfig
libpath: ./workspace/lib/libxml2.so
links:
  - -lz
  - -llzma
  - -lm
include_dir:
  - ./workspace/include
timeout: 60
timeout_unit: 10
