# Config
name: cjson
srcdir: ./workspace/src/cJSON
postfix:
  - .h
  - .hpp
  - .hxx
corpus_dir: ./workspace/corpus
fuzzdict: ./workspace/dict/json.dict
# CppConfig
libpath: ./workspace/lib/libcjson.a
include_dir:
  - ./workspace/include
timeout: 60
timeout: 10
