# Config
name: libtiff
srcdir: ./workspace/src/libtiff
postfix:
  - .h
  - .hpp
  - .hxx
fuzzdict: ./workspace/dict/tiff.dict
corpus_dir: ./workspace/corpus
# CppConfig
libpath: ./workspace/lib/libtiff.so
links:
  - -lz
  - -llzma
  - -lm
include_dir:
  - ./workspace/include
timeout: 60
timeout_unit: 10
