# Config
name: libpcap
srcdir: ./workspace/src/libpcap
postfix:
  - .h
  - .hpp
  - .hxx
corpus_dir: ./workspace/corpus
# CppConfig
libpath: ./workspace/lib/libpcap.a
include_dir:
  - ./workspace/include
timeout: 60
timeout: 10
