# Config
name: libaom
srcdir: ./workspace/src/aom
postfix:
  - .h
  - .hpp
  - .hxx
corpus_dir: ./workspace/corpus
# CppConfig
libpath: ./workspace/lib/libaom.so
links:
  - -lz
  - -llzma
  - -lm
include_dir:
  - ./workspace/include
timeout: 60
timeout_unit: 10
