# Config
name: zlib
srcdir: ./workspace/src/zlib
postfix:
  - .h
  - .hpp
  - .hxx
corpus_dir: ./workspace/corpus
# CppConfig
libpath: ./workspace/lib/libz.a
include_dir:
  - ./workspace/include
timeout: 60
timeout_unit: 10
